name: Call security pipeline
on:
  workflow_dispatch:
  pull_request:
jobs:
  code-scan:
    uses: "stirn/security-pipeline/.github/workflows/include-inside.yml@main"
    secrets: inherit
    # permissions:
    #   issues: write
    #   pull-requests: write
    #   contents: read
